### ISSUE TITLE
Double tap circle to insert a period.

### ISSUE THREAD

**Issue by Nikoichu** [8VIM/8VIM#265]
This feature is present in most other keyboards (double tap space to insert period and a space after it) and will help new users get used to the keyboard faster. Furthermore, the period is currently too hard to insert for such a commonly used symbol -  you have to make a full circle. Instead if it's on double tap of the central circle (space), another symbol could take its current place, like : ; " & _

P.S. I'm a new user and it took me a good two minutes to write only the title 😅
Love the keyboard tho, keep working on it!

**Comment by levigutt** [comment]
Sometimes I need to input multiple spaces, for indenting or aligning text. This feature would get in the way of that.

If a feature like this is added, it'd be great if there was an option to disable it :)

**Comment by martin-braun** [comment]
How about this: If you finalize the letter by moving from the center to the bottom before lifting the finger, it will undo the last space and insert `. `?

Sadly I think this would break custom `inside_circle`/`bottom`/`no_touch` mappings, but maybe it's worth doing so, because it would feel very natural to me.

**Comment by levigutt** [comment]
I do this when I don't want a trailing space 😅

**Comment by martin-braun** [comment]
@levigutt You are right.

Correction: `C-B-C` could insert `. `, this actually work. You don't need any app changes for that, see this mapping:

```yaml
    - movement_sequence:
        - inside_circle
        - bottom
        - inside_circle
      lower_case: .
      upper_case: .
```

Unfortunately, my suggestion would clash with the suggestion to have at least two cells in the movement, and we definitely should keep this suggestion up. Otherwise, you would accidentally triggering dots that you might not want to print in the first place.

**Comment by martin-braun** [comment]
Ok, so I tried to map these:

```yaml
    - movement_sequence:
        - no_touch
        - bottom
        - inside_circle
      lower_case: .
      upper_case: .
    - movement_sequence:
        - no_touch
        - bottom
        - inside_circle
        - bottom
        - no_touch
      lower_case: .
      upper_case: .
    - movement_sequence:
        - no_touch
        - bottom
        - inside_circle
        - bottom
        - inside_circle
      lower_case: ","
      upper_case: ","
    - movement_sequence:
        - no_touch
        - bottom
        - inside_circle
        - bottom
        - inside_circle
        - bottom
        - no_touch
      lower_case: ","
      upper_case: ","
```

The idea is that you write your word, but go into the bottom cell, lift your finger to not insert any space, then touch the bottom cell and move up into the center, lift your finger and it would insert a dot with a final space.

Unfortunately, 8vim seems to disallow this map for any reason. @flide is there a reason to disallow `B-C` maps? Yes, I know `L-C`, `T-C` and `R-C` are blocked, since they are reserved, but it seems `B-C` is not used and blocked for future use only?

Maybe it would make sense to give the user a quicker way to insert dots and commas in the same way I presented above? I also think a faster method to insert `. ` is needed for chat flow with the keyboard.

**Comment by flide** [comment]
If your map happens to be a subset of an already defined map, it is considered invalid.

**Comment by martin-braun** [comment]
@flide Ok, I get it, because the center cell doesn't require me to lift a finger, so it will not accept my map, because there is something bigger that could come. My comma keymap is just an example to this. Now I simplified it to: 

```yaml
    - movement_sequence:
        - no_touch
        - bottom
        - inside_circle
      lower_case: .
      upper_case: ","
```

There is no other movement sequence starting with `no_touch`/`bottom`/`inside_circle`, but it still doesn't work.

<img width="1128" alt="Screenshot 2023-06-19 at 13 50 28" src="https://github.com/flide/8VIM/assets/24259245/4cd505a4-4b91-422c-9ae4-16e821c488f6">
